### ISSUE TITLE
v0.10.1 does not appear as an update

### ISSUE THREAD

**Issue by Taomyn** [hassio-addons/addon-log-viewer#62]
# Problem/Motivation

My HAAS is fully up to date, other add-ons update fine, but this one seems to be stuck on v0.9.1

## Expected behavior

Update to 0.10.1 is available

## Actual behavior

![image](https://user-images.githubusercontent.com/4365929/110432312-39114f80-80af-11eb-8f83-725dc12ed885.png)

**Comment by frenck** [comment]
Interesting, it did not pick up the version before this one either. Something to research, thanks for reporting!

**Comment by Taomyn** [comment]
Any luck finding out why it's not appearing?

**Comment by frenck** [comment]
If I did you would have seen that here:...

**Comment by NicoSomerwil** [comment]
Thanks for the effort in correcting this (for me minor) issue!
Just noticed that uninstall and (re-)install the log viewer again brings 0.9.1 back. Just to let you know this. 
Good luck and thanks for all your great hassio-addons!!

**Comment by grodzik** [comment]
Since I also was hit by lack of update on this integration, I may have a clue about the issue. Problem may be with sorting versions. If we sort them normally (so not treating it as versions, but rather as a string), it turns out, that version v0.10.0 is after v0.1.0 and before v0.2.0 - hence not newer than version 0.9.x

You can compare output of the two following commands (first normal sort, second version sort)

    curl -L -s https://api.github.com/repos/hassio-addons/addon-log-viewer/tags | sed -n 's/.*\(v0.[^"]\+\).*/\1/p' | uniq | sort

    curl -L -s https://api.github.com/repos/hassio-addons/addon-log-viewer/tags | sed -n 's/.*\(v0.[^"]\+\).*/\1/p' | uniq | sort -V

So the fix actually may be needed in Home Assistant itself - or release version v.1.0.0 ;)
